version: 2.1

orbs:
  terraform: 'circleci/terraform@1.2.1'
  ansible: 'orbss/ansible@0.2.3'

jobs:
  Git_Clone:
    executor: terraform/default
    steps:
      - run:
          command: >-
                GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
                git clone https://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@github.com/Mayur-Chavan7759/Terraform.git
          name: GIT Clone Terraform repository

      - run:
          command: >-
                GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
                git clone https://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@github.com/Mayur-Chavan7759/Ansible.git
          name: GIT Clone Ansible repository

      - persist_to_workspace:
          root: .
          paths: .

    working_directory: ~src

  Terraform_Setup:
    executor: terraform/default
    steps:
      - attach_workspace:
          at: .
      
      - run:
          name: terraform init
          command: terraform -chdir="./Terraform" init

      - run:
          name:  terraform validate
          command: terraform -chdir="./Terraform" validate
          
      - run:
          name: terraform plan
          command: terraform -chdir="./Terraform" plan -var-file="values.tfvars"

      - persist_to_workspace:
          root: .
          paths: .

    working_directory: ~src

  Terraform_Setup_Apply:
    executor: terraform/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform Apply
          command: terraform -chdir="./Terraform" apply -var-file="values.tfvars" --auto-approve
      - run:
          command: |
                cd Ansible
                ls
                cd Terraform
                ls
    working_directory: ~src

workflows:
  circleci_terraform_ansible_integration: 
    jobs:
      - Git_Clone
      - Terraform_Setup:
          context: terraform
          requires:
            - Git_Clone
      - Hold:
          type: approval
          requires:
            - Terraform_Setup
      - Terraform_Setup_Apply:
          context: terraform
          requires:
            - Hold
