version: 2.1

orbs:
  terraform: 'circleci/terraform@2.1'

jobs:
  Git_Clone:
    executor: terraform/default
    steps:
      - run:
          command: >-
                GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
                git clone https://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@github.com/Mayur-Chavan7759/Terraform.git
          name: GIT Clone Terraform repository

      - run:
          command: >-
                GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
                git clone https://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@github.com/Mayur-Chavan7759/Ansible.git
          name: GIT Clone Ansible repository

      - persist_to_workspace:
          root: .
          paths: .

    working_directory: ~src

  Terraform_Setup:
    executor: terraform/default
    steps:
      - attach_workspace:
          at: .
      
      - run:
          name: terraform init
          command: terraform -chdir="./Terraform" init

      - run:
          name: terrraform validate
          command: terraform -chdir="./Terraform" validate
          context: terraform
          
      - run:
          name: terraform plan
          command: terraform -chdir="./Terraform" plan -var-file="values.tfvars"

workflows:
  circleci_terraform_ansible_integration: 
    jobs:
      - Git_Clone
      - Terraform_Setup:
          requires:
            - Git_Clone