version: 2.1

orbs:
  terraform: 'circleci/terraform@2.1'

jobs:
  my_first_job:
    executor: terraform/default
    steps:
      - run:
          command: >-
                GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
                git clone https://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@github.com:Mayur-Chavan7759/Terraform.git
          name: GIT Clone Terraform repository

      - run:
          command: |
              cd Terraform
              ls
workflows:
  circleci_terraform_ansible_integration: 
    jobs:
      - my_first_job
